### ISSUE TITLE
Please update to official github repository

### ISSUE THREAD

**Issue by ecsv** [cl4u2/ap51flash_old#1]
Hi,

it seems like your git repository is using different commit ids (and incorrect author information) than the "official" one at https://github.com/ap51-flash/ap51-flash and is outdated. Just to the history of the repository (starting with the OpenMesh repo):

1. source was served via http://dev.open-mesh.com/downloads/svn/ap51-flash
2. source was converted to git and made available via https://dev.cloudtrax.com/git/ap51-flash.git
3. git repository was moved to https://github.com/ap51-flash/ap51-flash to allow others to contribute to it
   * I have now also changed https://dev.cloudtrax.com/git/ap51-flash.git to redirect to this repository

The version now served here is outdated and doesn't contain many of the newer HW models. It would therefore be awesome to get this repository in sync with the central ap51-flash repository. But I would propose not to throw all of your commits away because some of the repositories on github are actually using specific commit ids of your repository. My suggestion:

1. recreate this repository as a proper github fork of https://github.com/ap51-flash/ap51-flash under the name https://github.com/cl4u2/ap51flash
2. push your old master branch under a different name ("old-commit-ids"?) to this repository to preserve the old commit ids

**Comment by cl4u2** [comment]
Hi, @ecsv. Probably I have used git-svn to convert from the old svn repo to git. Thank you. I will follow your advice.

**Comment by cl4u2** [comment]
Done: https://github.com/cl4u2/ap51-flash
